# Data import



In [2]:
import pandas as pd
import numpy as np
from pyspark import RDD
from pyspark import SparkContext
#data1 is a copy of analysis songs part0000
d=sc.pickleFile("analysis_0000")


In [2]:
sparkDF = d.map(lambda x: str(x)).map(lambda w: w.split(',')).toDF()

In [3]:
df=sparkDF.toPandas()

In [4]:
s=d.collect()


In [5]:
s[0]

('TRAAAAW128F429D538',
 array([ (22050, 'a222795e07cd65b7a530f1346f520649',  0.,  218.93179,  0.247,  0., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,  0.736, -11.197, 0,  0.636,  218.932,  92.198, 4,  0.778, 'TRAAAAW128F429D538')],
       dtype=[('analysis_sample_rate', '<i4'), ('audio_md5', 'S32'), ('danceability', '<f8'), ('duration', '<f8'), ('end_of_fade_in', '<f8'), ('energy', '<f8'), ('idx_bars_confidence', '<i4'), ('idx_bars_start', '<i4'), ('idx_beats_confidence', '<i4'), ('idx_beats_start', '<i4'), ('idx_sections_confidence', '<i4'), ('idx_sections_start', '<i4'), ('idx_segments_confidence', '<i4'), ('idx_segments_loudness_max', '<i4'), ('idx_segments_loudness_max_time', '<i4'), ('idx_segments_loudness_start', '<i4'), ('idx_segments_pitches', '<i4'), ('idx_segments_start', '<i4'), ('idx_segments_timbre', '<i4'), ('idx_tatums_confidence', '<i4'), ('idx_tatums_start', '<i4'), ('key', '<i4'), ('key_confidence', '<f8'), ('loudness', '<f8'), ('mode', '<i4'), ('mode_confidence',

In [6]:
df.head()

_1               _2  \
0  ('TRAAAAW128F429D538'   array([ (22050   
1  ('TRAAABD128F429CF47'   array([ (22050   
2  ('TRAAADZ128F9348C2E'   array([ (22050   
3  ('TRAAAEF128F4273421'   array([ (22050   
4  ('TRAAAFD128F92F423A'   array([ (22050   

                                    _3    _4           _5       _6    _7  _8  \
0   'a222795e07cd65b7a530f1346f520649'    0.    218.93179    0.247    0.   0   
1   'bb9771eeef3d5b204a3c55e690f52a91'    0.    148.03546    0.148    0.   0   
2   'fa329738005ca53715d9f7381a0d1fe3'    0.    177.47546    0.282    0.   0   
3   '43cd1abd45d5a2dda16a3c65b4963bd4'    0.    233.40363       0.    0.   0   
4   '580a8fe08ef0f1c7734b84547d7a8bc7'    0.    209.60608    0.066    0.   0   

   _9 _10     ...                        _85      _86        _87      _88  \
0   0   0     ...       ('start_of_fade_out'   '<f8')   ('tempo'   '<f8')   
1   0   0     ...       ('start_of_fade_out'   '<f8')   ('tempo'   '<f8')   
2   0   0     ...       ('start_of_fade_out'   '<f8')   ('tempo'   '<f8')   
3   0   0     ...       ('start_of_fade_out'   '<f8')   ('tempo'   '<f8')   
4   0   0     ...       ('start_of_fade_out'   '<f8')   ('tempo'   '<f8')   

                  _89      _90                            _91      _92  \
0   ('time_signature'   '<i4')   ('time_signature_confidence'   '<f8')   
1   ('time_signature'   '<i4')   ('time_signature_confidence'   '<f8')   
2   ('time_signature'   '<i4')   ('time_signature_confidence'   '<f8')   
3   ('time_signature'   '<i4')   ('time_signature_confidence'   '<f8')   
4   ('time_signature'   '<i4')   ('time_signature_confidence'   '<f8')   

            _93         _94  
0   ('track_id'   'S32')]))  
1   ('track_id'   'S32')]))  
2   ('track_id'   'S32')]))  
3   ('track_id'   'S32')]))  
4   ('track_id'   'S32')]))  

[5 rows x 94 columns]

In [7]:
d2=sc.pickleFile("section_start_0000")
d2.collect()

[('TRAAAAW128F429D538',
  array([   0.     ,    7.74554,   36.44331,   43.61667,   75.17954,
           90.1827 ,  135.77195,  164.23964,  189.03133,  198.20273])),
 ('TRAAABD128F429CF47',
  array([   0.     ,    8.1777 ,   19.52952,   38.84063,   50.22563,
           70.44611,   87.35373,  103.25887,  140.00968])),
 ('TRAAADZ128F9348C2E',
  array([   0.     ,   37.88678,   49.43939,   68.63657,   98.89331,
          113.23546,  131.78364,  169.35795])),
 ('TRAAAEF128F4273421',
  array([   0.     ,   20.38681,   27.94943,   55.12454,   67.71832,
           98.89772,  125.58011,  152.71904,  167.30522,  188.42158,
          225.09249])),
 ('TRAAAFD128F92F423A',
  array([   0.     ,    8.00636,   23.26694,   67.22425,   74.15257,
          143.54666,  161.1341 ,  174.08937,  200.45554])),
 ('TRAAAMO128F1481E7F',
  array([   0.     ,    6.82464,   46.38231,   69.10539,   85.02519,
           94.75319,  123.2464 ,  175.38845,  191.37967,  201.92289,
          218.16345,  242.89234,  254.72

# Data analysis
In order to get a better grasp of the characteristics of a summer hit, we order our songs realease mont and year, and compare the features between:
- The summer songs (between May and August) and the other songs of a same year
- The summer songs of each year

The considered features would be :

__analysis-song__

- danceability
- duration
- energy
- key
- loudness
- mode (Maj/min)
- tempo
- time signature (beats per measure) 

__other files__
- artiste longitude/latitude
- lyrics (sentiment analysis ?)
- language
- artist hotness
- genre (other dataset ? )

The success of each song will be evaluated with the song hotness feature and its ranking in the billboard ranking of summer hits 

https://www.billboard.com/articles/news/513524/summer-songs-1985-present-top-10-tunes-each-summer-listen

http://docs.7digital.com/#standard-response-objects_Release


# Feature overview
From the Millonsong documentation, we found that the tracks had been chosen amongst the most "familiar" artists according to The Echo Nest, and some extreme songs according to the features defined by The Echo Nest. To get a grasp of these features, we will plot them by year for the subset.
VIOLIN PLOT

In [3]:
import seaborn as sns
def plot_feature_by_year(data_feature,name_feature):
    #split between hotness >0.6 (or add column ?
    sns.set(style="whitegrid", palette="pastel", color_codes=True)

    # Load the example tips dataset
    tips = sns.load_dataset("tips")

    # Draw a nested violinplot and split the violins for easier comparison
    sns.violinplot(x="Year", y=name_feature, hue="hotness", data=data_feature, split=True,
                   inner="quart", palette={"h>0.6": "b", "total": "y"})
    sns.despine(left=True)
    